"""
Pydantic schemas for Data Mirage application.
"""

from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserProfile,
    UserList,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    EmailVerification,
    UserLogin,
    TokenResponse,
    RefreshToken,
    SessionResponse,
    UserSettings,
)

from .dataset import (
    DatasetBase,
    DatasetCreate,
    DatasetUpdate,
    DatasetMetadata,
    FileInfo,
    DatasetResponse,
    DatasetDetail,
    DatasetWithData,
    DatasetList,
    DatasetUpload,
    DatasetProcessingStatus,
    ColumnSelection,
    DatasetVersion,
    DatasetStats,
    DatasetSearch,
)

from .ml import (
    ReductionMethod,
    ClusteringMethod,
    MLConfig,
    TSNEConfig,
    UMAPConfig,
    PCAConfig,
    KMeansConfig,
    DBSCANConfig,
    HDBSCANConfig,
    AgglomerativeConfig,
    AnomalyDetectionConfig,
    DataPoint,
    Cluster,
    ClusterAnalysis,
    ProcessingMetadata,
    ProcessingResult,
    ProcessingRequest,
    ProcessingProgress,
    VisualizationConfig,
    ModelPerformance,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate", 
    "UserUpdate",
    "UserResponse",
    "UserProfile",
    "UserList",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "UserLogin",
    "TokenResponse",
    "RefreshToken",
    "SessionResponse",
    "UserSettings",
    
    # Dataset schemas
    "DatasetBase",
    "DatasetCreate",
    "DatasetUpdate", 
    "DatasetMetadata",
    "FileInfo",
    "DatasetResponse",
    "DatasetDetail",
    "DatasetWithData",
    "DatasetList",
    "DatasetUpload",
    "DatasetProcessingStatus",
    "ColumnSelection",
    "DatasetVersion",
    "DatasetStats",
    "DatasetSearch",
    
    # ML schemas
    "ReductionMethod",
    "ClusteringMethod",
    "MLConfig",
    "TSNEConfig",
    "UMAPConfig",
    "PCAConfig",
    "KMeansConfig",
    "DBSCANConfig",
    "HDBSCANConfig",
    "AgglomerativeConfig",
    "AnomalyDetectionConfig",
    "DataPoint",
    "Cluster",
    "ClusterAnalysis",
    "ProcessingMetadata", 
    "ProcessingResult",
    "ProcessingRequest",
    "ProcessingProgress",
    "VisualizationConfig",
    "ModelPerformance",
]